### ISSUE TITLE
Map auto-centering/sizing with "drawer"

### ISSUE THREAD

**Issue by igorrosenberg** [chadn/mapfilter#5]
*\* Problem description **

Open firefox browser in a 'small' window (like 1300x900).
Load this test cal (don'tforget to specify dates): 
    index.html?gc=0ei0284so407vu24o7o0q5ares%40group.calendar.google.com&sd=2010-01-01&ed=2013-1-01
There are three events defined. The one on the right (French/German border) is hidden under the drawer. 

*\* Idea for solution **

Map area should depend on the locations in Gcal (implemented) and the div size for the map (todo: dimension to determine at runtime)

**Comment by chadn** [comment]
Issue reworded:  

Before "drawer", the visible part of the map was all there was.  Now drawer can cover map, since map is entire browser window.  Since map can be partially covered, some markers can be hidden.

Solution options:
1. Make drawer partially transparent
2. Change map/drawer so map is not hidden under drawer

**Comment by chadn** [comment]
Fix is not ideal, fixing completely creates new issues.   Closing for now.
