### ISSUE TITLE
In the drawer, the "where" link labelled 'orig' does nothing

### ISSUE THREAD

**Issue by igorrosenberg** [chadn/mapfilter#6]
Load this test cal (don't forget to specify dates):
        index.html?gc=0ei0284so407vu24o7o0q5ares%40group.calendar.google.com&sd=2010-01-01&ed=2013-1-01
There are three events defined, and appear in the drawer; in the column "where", there is for each a link '(orig)' . Clicking on it does nothing. What should it do?

**Comment by chadn** [comment]
It has no action, but if you hover it revealed the original address, the one from the calendar, vs the one displayed which is a verified address from google's geocoder.

I use past tense because I just changed it - now you just hover over the address to see original.

Ideally it should not be a link, but need to reveal that info easily and compactly.
